In [17]:
import numpy as np

In [18]:
np.random.seed(0)

In [19]:
x=[[1,2,3,2.5],
  [2.0,5.0,-1.0,2.0],
  [-1.5,2.7,3.3,-0.8]]

In [20]:
class layer_dense:
    def __init__(self,n_inputs,n_neurons):
        self.weights=0.10*np.random.randn(n_inputs,n_neurons)
        self.bias=np.zeros((1,n_neurons))
    def forward(self,inputs):
        self.output=np.dot(inputs,self.weights)+self.bias

layer1=layer_dense(4,5)
layer2=layer_dense(5,3)

layer1.forward(x)
#print(layer1.output)
layer2.forward(layer1.output)
print(layer2.output)

[[-0.07349747  0.20606039 -0.09895969]
 [ 0.00215285  0.09019504 -0.10555064]
 [ 0.03332613  0.07729937 -0.12740738]]
